language: ruby
cache: bundler
dist: bionic
sudo: false
before_script:
  - travis_retry gem install rails --version '~> 5.1.0'

rvm:
  - 2.7.6
  - 3.0.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
